# Run reboot command asynchronously and without polling, giving ansible time for cleanup
- name: "Restart"
  become: yes
  shell: sleep 2 && /sbin/shutdown -r now "Rebooting"
  async: 1
  poll: 0

# New module - wait for host to come back
- name: "Await host coming back up"
  wait_for_connection:
   delay: 5
   sleep: 1
   timeout: 120
