---
# Apply this to test group only
- hosts: test_group
  remote_user: pi
  become: yes
  tasks:
#  - debug: msg="Starting pi initial setup"
  - import_tasks: common_tasks/getserial.yaml
    static: yes  
  - set_fact:
     rpi_serial: "{{ rpi_serial_output.stdout }}"
     rpi_configfile: "{{ lookup('ini', 'configfile section=' + rpi_serial_output.stdout + ' file=boards.ini')|quote }}"
  - debug: msg="Machine {{ inventory_hostname }} has actual hostname ({{ ansible_hostname }})"
  - debug: msg="Board serial is {{ rpi_serial }}"
  - debug: msg="Configuration file is {{ rpi_configfile }}"
#  - import_tasks: common_tasks/updateaptpackages.yaml
#    static: yes
#  - import_tasks: common_tasks/restartandawait.yaml
#    static: yes
  - debug: msg="Done updating apt, now prepping python"
  - import_tasks: common_tasks/installpippackages.yaml
    static: yes
